### ISSUE TITLE
Setup and repo issues

### ISSUE THREAD

**Issue by KOLANICH** [takluyver/backcall#2]
1 Use setuptools instead of distutils
2 in tests add the parent directory in module searching path

Optional:
3 move metadata into setup.cfg
4 use setuptools_scm to get version from git
5 add some auxilary files: .editorconfig

An example is
https://github.com/KOLANICH/HDDModelDecoder.py

Based on Kennet Reiz's boilerplate.

**Comment by takluyver** [comment]
Thanks for the reminder. I've updated the packaging, though I've done it a bit differently.

**Comment by KOLANICH** [comment]
![Standards](https://imgs.xkcd.com/comics/standards.png)
