### ISSUE TITLE
include LICENSE in tar-ball

### ISSUE THREAD

**Issue by arunpersaud** [takluyver/backcall#3]
would be great to include the LICENSE in the tar-ball. Especially since there are different versions of the BSD license around (2-clause, 3 clause,...). This would make packaging for linux distribution easier (at least for openSUSE where I just created the backcall package).

**Comment by takluyver** [comment]
Thanks, I'll make sure it's there for the next release. I assume that now
you've packaged this release, it's not worth making a new release just for
that change by itself?

**Comment by arunpersaud** [comment]
correct, next release (whenever you plan one) is fine for me. Thanks!

**Comment by takluyver** [comment]
0.2.0 is out, with the LICENSE file in the tarball. :-)
