### ISSUE TITLE
Publish wheel ? 

### ISSUE THREAD

**Issue by Carreau** [takluyver/backcall#7]
It seem like backcall is one of the 360 top PyPI packages that does not have a published wheel: 

https://pythonwheels.com/

What do you think of publishing one ?

**Comment by takluyver** [comment]
I don't know whether to be nervous that it's in the top 360, or pleased that we're only on issue #7 despite that. Anyway, yup, time for a new release with a wheel.

**Comment by takluyver** [comment]
(Presumably its position is just pulled along by whichever part of IPython/Jupyter I managed to use it in)

**Comment by takluyver** [comment]
0.2.0 is out now, complete with a wheel.

**Comment by Carreau** [comment]
Thanks ! And missing you.
