### ISSUE TITLE
Copyright information for version 0.1

### ISSUE THREAD

**Issue by stefan-hdt** [takluyver/backcall#9]
Hello,

I wonder which copyright statement applies for version 0.1 of this component. The master branch states "Copyright (c) 2014, Thomas Kluyver All rights reserved." at https://github.com/takluyver/backcall/blob/master/LICENSE.

I would appreciate it if you could clarify that just to avoid any confusion. :-)

Thanks!

Stefan

**Comment by takluyver** [comment]
Hi Stefan, you can take that LICENSE file (as it is in 0.2) to apply to 0.1 as well if you want.

**Comment by stefan-hdt** [comment]
Thanks a lot.
